### ISSUE TITLE
Fails to stop autoplay on USA Today

### ISSUE THREAD

**Issue by fcntl** [Eloston/disable-html5-autoplay#74] opened 2016-08-08 20:19 UTC
http://www.usatoday.com/story/sports/2016/08/07/finger-pointing-sets-up-us-russian-womens-swim-showdown/88381764/

(Chrome 52, Windows 10)

**Comment by Eloston** [comment] 2016-08-08 20:23
Could you try the solution in #39?

**Comment by legovini** [comment] 2016-08-08 21:03
I don't have Flash, but it does autoplay here. (Chromium 52, Debian system).

**Comment by Eloston** [comment] 2016-08-08 21:12
Closing as duplicate of #47. See https://github.com/Eloston/disable-html5-autoplay/issues/47#issuecomment-238378996

**Closed** 2016-08-08 21:13 UTC
Labels: duplicate
