### ISSUE TITLE
Toggle button doesn't remember whitelisted URLs (Opera)

### ISSUE THREAD

**Issue by ShintoPlasm** [Eloston/disable-html5-autoplay#20] opened 2015-10-14 21:08 UTC
When I toggle the button to 'Nothing' on YouTube, the extension remembers my selection during the current session. After restarting the browser, it is as if I never whitelisted the YouTube domain and the toggle is back to blocking autoplay.

I'm using Opera stable (32.0.1948.69) on Win10 Home, Flash PPAPI installed, and third-party cookies blocked in the preferences (with YouTube NOT whitelisted).

**Comment by ShintoPlasm** [comment] 2015-10-14 21:12
Ahem, just saw this in the extension description on the main page: "(will be saved across browser sessions in the future)"

Never mind then...

**Comment by Eloston** [comment] 2015-10-14 21:13
This feature request is a duplicate of #12

**Closed by Eloston** 2015-10-14 21:13 UTC
