### ISSUE TITLE
The plugin disables the autoplay but there is no option to play the content on demand

### ISSUE THREAD

**Issue by romrozen** [Eloston/disable-html5-autoplay#85] opened 2016-10-15 15:28 UTC
One of the examples is the following page:

http://www.ynet.co.il/articles/0,7340,L-4866658,00.html

So if I do want to see the video I don't have a choice besides disabling the plugin and refresh the page again.

**Comment by Eloston** [comment] 2016-10-15 17:51
This is a duplicate of #17.

**Closed** 2016-10-15 17:51 UTC
Labels: duplicate
