### ISSUE TITLE
Does not save white list between browser sessions

### ISSUE THREAD

**Issue by kirkerafael** [Eloston/disable-html5-autoplay#25] opened 2015-10-28 10:32 UTC
If I choose "Nothing" from the menu, which should stop this extension from stopping videos in whole domain, it works just untill I reset the browser.

**Comment by Eloston** [comment] 2015-10-28 19:58
This is a duplicate of #12. This feature (now called mode rules) will be released with version 0.6. You can check the status of the 0.6 milestone here: https://github.com/Eloston/disable-html5-autoplay/milestones/0.6

Additionally, the README.md on GitHub, the Chrome Webstore description, and the Opera addons description say in the third bullet point of the features, "(will be saved across browser sessions in the future)"

**Closed by Eloston** 2015-10-28 19:58 UTC
