### ISSUE TITLE
HTML5 Autoplaying interfering with Soundcloud

### ISSUE THREAD

**Issue by K-Steel** [Eloston/disable-html5-autoplay#113] opened 2017-01-23 02:53 UTC
I've noticed recently my soundcloud wasn't working. I'd play the song but it would stop immediately. After troubleshooting the only thing that got it working was disabling HTML autoplay for soundcloud.

**Comment by Eloston** [comment] 2017-01-23 19:39
Duplicate of #18.

**Closed by Eloston** 2017-01-23 19:39 UTC
