### ISSUE TITLE
Stops ALL playback on Soundcloud, not just auto play.

### ISSUE THREAD

**Issue by martin-nef** [Eloston/disable-html5-autoplay#163] opened 2017-05-18 15:12 UTC
Using Chrome Version 58.0.3029.110 (64-bit) and Windows 10 and the addon stops all playback on the Soundcloud web player no matter what song, instead of only stopping auto play.

P.S. Couldn't figure out what was causing this at first but it was easily solved by creating a rule "soundcloud.com nothing" in the settings.

**Comment by Eloston** [comment] 2017-05-19 06:10
Duplicate of #18.

**Closed by Eloston** 2017-05-19 06:10 UTC
