### ISSUE TITLE
While videos are not autoplaying, they're still preloading video data

### ISSUE THREAD

**Issue by nick-s-b** [Eloston/disable-html5-autoplay#82] opened 2016-10-05 01:39 UTC
If you go on pretty much any Bloomberg.com page, for example, and you scroll down, you'll notice that little video player follows you. While it's not autoplaying the video, it's preloading and downloading the video needlessly (if you're bandwidth constrained or on mobile you'll notice this).

Can we PLEASE add an option to stop that behavior? I believe this can be fixed with `preload="none"` tag.

Thank you for an excellent extension!

**Comment by Eloston** [comment] 2016-10-05 01:45
Thanks for using the extension!

> I believe this can be fixed with preload="none" tag.

It wasn't that simple the last time I looked. JavaScript can also force the loading. Also, if some videos don't preload, the video players won't be able to work.

Also, this happens to be a duplicate of #9.

**Closed by Eloston** 2016-10-05 01:45 UTC
