### ISSUE TITLE
soundcloud

### ISSUE THREAD

**Issue by lagun** [Eloston/disable-html5-autoplay#124] opened 2017-02-19 08:02 UTC
it block soundcloud to play music ,when i use disable autoplay. 
watch my video to saw my problem.
https://sendvid.com/u758t6vd

**Comment by ifreaker** [comment] 2017-02-25 19:40
+1
Have the same problem

**Comment by Eloston** [comment] 2017-05-02 03:41
Duplicate of #18.

**Closed by Eloston** 2017-05-02 03:41 UTC
