### ISSUE TITLE
USA Today videos still autoplay

### ISSUE THREAD

**Issue by bconway** [Eloston/disable-html5-autoplay#91] opened 2016-10-29 19:28 UTC
Greetings! With the default block setting, the video here still autoplays:

http://www.usatoday.com/story/news/nation/2016/10/29/ag-lynch-objected-fbi-director-going-public-email-review/92949970/

The only other extension I use is uBlock Origin. Thanks.

**Comment by Eloston** [comment] 2016-10-31 20:42
Thanks for reporting. I will add this link to the pre-existing issue report.

Closing as duplicate of #47.

**Closed by Eloston** 2016-10-31 20:42 UTC

**Comment by bconway** [comment] 2016-11-04 18:39
Apologies, should've searched.
