### ISSUE TITLE
USA Today autoplay with autoplay disabled. 

### ISSUE THREAD

**Issue by wlinde** [Eloston/disable-html5-autoplay#192] opened 2017-08-21 14:24 UTC
The video at this link plays with autoplay enabled. I have used chrome to disable flash as well. 

https://www.usatoday.com/story/news/politics/2017/08/21/secret-service-cant-pay-agents-because-trumps-frequent-travel-large-family/529075001/

**Comment by Dynamic-Gravity** [comment] 2017-08-21 14:50
Can confirm. Although, for me the video did not play automatically but once I scrolled down then the video went into the bottom right corner and started auto play.

**Comment by Eloston** [comment] 2017-08-21 22:49
Duplicate of #47

**Closed by Eloston** 2017-08-21 22:49 UTC
