### ISSUE TITLE
Soundcloud.com audio won't start manually on Chrome

### ISSUE THREAD

**Issue by shenkin** [Eloston/disable-html5-autoplay#154] opened 2017-05-01 06:33 UTC
I have autoplay disabled on Chrome, but the following Soundcloud audio won't play even when attempted manually. It plays on Firefox, where I don't have "Disable HTML5 Autoplay" installed.

https://soundcloud.com/uwlibraries/porter01001-9

I'm using Chrome 58.0.3029.81 on MacOS Sierra 10.12.4.

**Comment by Eloston** [comment] 2017-05-02 03:41
Duplicate of #18.

**Closed by Eloston** 2017-05-02 03:41 UTC
