### ISSUE TITLE
Feature request: Enable/disable based on path

### ISSUE THREAD

**Issue by ekimekim** [Eloston/disable-html5-autoplay#168] opened 2017-06-02 19:36 UTC
Sometimes, there are certain pages of a site which you want to allow autoplay on, but not the entire site. A motivating example: Block autoplaying channel page videos on youtube (pages with path `www.youtube.com/channel/*`) without blocking autoplaying normal videos (pages with path `www.youtube.com/watch`.

This would be an extension of the existing mode rules syntax, and could be based on path prefix or (ideally) a wildcard match as in my example above.

Love this extension by the way. Thanks!

**Comment by Eloston** [comment] 2017-06-03 06:27
Thanks for the suggestion and compliment. This is a duplicate of #51

**Closed by Eloston** 2017-06-03 06:27 UTC

**Comment by ekimekim** [comment] 2017-06-03 06:28
Apologies. I tried to search, but obviously not well enough.

**Comment by Eloston** [comment] 2017-06-03 06:31
No problem. There are many other duplicates that I haven't consolidated into existing bug reports. Feature suggestions are rare enough that I tend to remember most of them.
