### ISSUE TITLE
http://www.baltimoresun.com/news/opinion/oped/bs-ed-lifelong-republican-20160817-story.html

### ISSUE THREAD

**Issue by betterth** [Eloston/disable-html5-autoplay#76] opened 2016-08-17 22:13 UTC
http://www.baltimoresun.com/news/opinion/oped/bs-ed-lifelong-republican-20160817-story.html

Autoplay audio still runs even with explicit autoplay-only mode rule added

**Comment by Eloston** [comment] 2016-08-17 22:17
Nothing's autoplaying for me. Do you have Flash installed? Is it enabled or disabled?

**Comment by betterth** [comment] 2016-08-17 22:22
Flash is installed by default in chrome, I have all flash plugins set to click - to - load.

When I use uMatrix and disable Other column 1st party request (video), I get no autoplay.

When I disable uMatrix and use uBlock Origin + Disable HTML5 Autoplay, I see

http://i.imgur.com/oaYJRdM.jpg

Where the video is click to load, but behind it, audio is playing and the UI clearly indicates content has loaded. Do you have sound enabled to hear it?

**Comment by betterth** [comment] 2016-08-17 22:23
Using chrome 53.0.2785.70 beta 64bit

**Comment by Eloston** [comment] 2016-08-17 22:25
I'm running ungoogled-chromium, and I didn't install the Flash plugin. From what your describing, this sounds a lot like #73. Could you try the link in the first post of that bug report and see if you have the same results?

**Comment by betterth** [comment] 2016-08-17 23:38
Yes both use -vfs-tech based video players, same issue.

Apologies, I should have taken the time to view your backlog prior to adding to it.

**Comment by Eloston** [comment] 2016-08-17 23:41
Nah it's okay. The Issue tracker is a bit messy at the moment, so I don't blame you for not looking through it.

I'll close this as a duplicate of #73 and add the link you found to it.

**Closed by Eloston** 2016-08-17 23:41 UTC
