### ISSUE TITLE
Extension breaks WebRTC

### ISSUE THREAD

**Issue by legovini** [Eloston/disable-html5-autoplay#55] opened 2016-05-30 09:02 UTC
Unfortunately this very useful extension breaks WebRTC. This is easy to reproduce, just go here:

https://janus.conf.meetecho.com/echotest.html

and try the echo test. The "Remote Stream" video will not start and there no "play" button to enable it. Allowing videos to autoplay fixes the issue.

**Comment by Eloston** [comment] 2016-05-30 18:45
This looks like a duplicate of #34.

**Closed by Eloston** 2016-05-30 18:45 UTC

**Comment by legovini** [comment] 2016-05-30 19:14
Agreed, sorry for the duplicate, I didn't spot the original report.
Looking forward to see #16 done. Thank you!
