### ISSUE TITLE
Google Hangouts video, no incoming sound

### ISSUE THREAD

**Issue by benridge** [Eloston/disable-html5-autoplay#108] opened 2017-01-12 02:36 UTC
I'm very thankful for this extension, it's been very useful for keeping autoplay videos from distracting me while browsing.

In Google Hangouts:
- html5 autoplay enabled
- start a video chat
I get video from the user, but no incoming sound. They can hear me but I can't hear them.
Disabling html5 autoplay fixes the problem.
I've set up a rule in the html5 autoplay options to disable for hangouts.google.com, and that works. I I suggest including the rule by default as users would not realize they are having the issue due to the extension.

**Comment by Eloston** [comment] 2017-01-12 07:08
We could hardcode this, but marking as duplicate of #34.

**Closed by Eloston** 2017-01-12 07:08 UTC

**Comment by DanGrayson** [comment] 2018-02-05 13:49
This problem still exists in 0.6.2, and bugged me for a week.
